backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header Image", name: "header", widget: "file"}
      - {label: "Give a brief overview of what you will cover", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Recommended Article Title", name: "recommendedName", widget: "string"}
      - {label: "Recommended Article Image", name: "recommendedImage", widget: "file"}
      - {label: "Recommended Article URL (Link)", name: "recommendedLink", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "portfolio"
    label: "Portfolio"
    folder: "src/pages/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: Title, name: title, widget: string}
      - {label: Header Image, name: "image", widget: file}
      - {label: Description, name: "description", widget: string}
      - {label: Date - Mon-Year / Left Column Title, name: jobDate, widget: string}
      - {label: Job Categories, name: leftColumn, widget: string}
      - {label: Right Hand Column - Top, name: portfolioDescription, widget: string}
      - {label: Big Image 1, name: "bigImageOne", widget: file}
      - {label: Quote Section, name: portfolioQuote, widget: string}
      - {label: Big Image 2, name: "bigImageOne", widget: file}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Portfolio Name, name: portfolioName, widget: string}
      - {label: Portfolio Image, name: portfolioImage, widget: image}
      - {label: Portfolio Link, name: portfolioLink, widget: string}
      - {label: "Tags", name: "tags", widget: "list"}

    - name: "work-with-me"
    label: "Work With Me"
    folder: "src/work-with-me/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: Title, name: title, widget: string}
      - {label: Header Image, name: "image", widget: file}
      - {label: Description, name: "description", widget: string}
      - {label: Date - Mon-Year / Left Column Title, name: jobDate, widget: string}
      - {label: Job Categories, name: leftColumn, widget: string}
      - {label: Right Hand Column - Top, name: portfolioDescription, widget: string}
      - {label: Big Image 1, name: "bigImageOne", widget: file}
      - {label: Quote Section, name: portfolioQuote, widget: string}
      - {label: Big Image 2, name: "bigImageOne", widget: file}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Portfolio Name, name: portfolioName, widget: string}
      - {label: Portfolio Image, name: portfolioImage, widget: image}
      - {label: Portfolio Link, name: portfolioLink, widget: string}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: Banner Slogan, name: title, widget: string}
          - {label: Header Image, name: "image", widget: file}
          - {label: Pinterest Grid 1 (Please use a small file), name: "imageOne", widget: file}
          - {label: Pinterest Grid 2 (Please use a small file), name: "imageTwo", widget: file}
          - {label: Pinterest Grid 3 (Please use a small file), name: "imageThree", widget: file}
          - {label: Pinterest Grid 4 (Please use a small file), name: "imageFour", widget: file}
          - {label: Pinterest Grid 5 (Please use a small file), name: "imageFive", widget: file}
          - {label: Pinterest Grid 6 (Please use a small file), name: "imageSix", widget: file}
          - {label: Pinterest Grid 7 (Please use a small file), name: "imageSeven", widget: file}
          - {label: Pinterest Grid 8 (Please use a small file), name: "imageEight", widget: file}
          - {label: Pinterest Grid 9 (Please use a small file), name: "imageNine", widget: file}
          - {label: Pinterest Grid 10 (Please use a small file), name: "imageTen", widget: file}
          - {label: Pinterest Grid 11 (Please use a small file), name: "imageEleven", widget: file}
          - {label: Pinterest Grid 12 (Please use a small file), name: "imageTwelve", widget: file}
          - {label: Pinterest Grid 13 (Please use a small file), name: "imageThirteen", widget: file}
          - {label: Pinterest Grid 14 (Please use a small file), name: "imageFourteen", widget: file}
          - {label: Pinterest Grid 15 (Please use a small file), name: "imageFifteen", widget: file}
          - {label: Thin Strip (Announcement Bar) Title / Blurb, name: "announcementBlurb", widget: string}
          - {label: Thin Strip (Announcement Bar) Title / Blurb Link, name: "announcementLink", widget: string}
          - {label: Thin Strip (Announcement Bar) Image, name: "announcementImage", widget: file}
          - {label: "Body Content", name: "body", widget: "markdown"}

      - file: "src/pages/about/index.md"
        label: "About"
        name: "about-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Wide Image", name: "full_image", widget: file}
          - {label: "Bottom Split Bar / Left Background", name: "leftBackground", widget: file}
          - {label: "Bottom Split Bar / Left Second Line", name: "leftTitle", widget: string}
          - {label: "Bottom Split Bar / Left Link", name: "leftLink", widget: string}
          - {label: "Bottom Split Bar / Right Background", name: "rightBackground", widget: file}
          - {label: "Bottom Split Bar / Right Title", name: "rightTitle", widget: string}
          - {label: "Bottom Split Bar / Right Description (Second Line)", name: "rightDescription", widget: string}
          - {label: "Bottom Split Bar / Right Link", name: "rightUrl", widget: string}

      - file: "src/pages/zero-to-hero-web-design-udemy-course/index.md"
        label: "Course"
        name: "course"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Wide Image", name: "full_image", widget: file}
          - {label: "Bottom Split Bar / Left Background", name: "leftBackground", widget: file}
          - {label: "Bottom Split Bar / Left Second Line", name: "leftTitle", widget: string}
          - {label: "Bottom Split Bar / Left Link", name: "leftLink", widget: string}
          - {label: "Bottom Split Bar / Right Background", name: "rightBackground", widget: file}
          - {label: "Bottom Split Bar / Right Title", name: "rightTitle", widget: string}
          - {label: "Bottom Split Bar / Right Description (Second Line)", name: "rightDescription", widget: string}
          - {label: "Bottom Split Bar / Right Link", name: "rightUrl", widget: string}



      - file: "src/pages/jargon/index.md"
        label: "Jargon"
        name: "jargon"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Wide Image", name: "full_image", widget: file}

      - file: "src/pages/portfolio/index.md"
        label: "My Portfolio"
        name: "portfolio-page"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "portfolio-page"}
          - {label: Title, name: "title", widget: string}
          - {label: Header Image, name: "image", widget: file}
          - {label: Description, name: "description", widget: string}
          - {label: Full Image, name: "fullImage", widget: file}
      
      - file: "src/pages/jayden/index.md"
        label: "Meet Jayden Szekely"
        name: "jayden"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Discoverable on Portfolio List - yes / no", name: "discoverable", widget: string}
          - {label: "Name", name: "title", widget: string}
          - {label: "Wide Image", name: "full_image", widget: file}
          - {label: "Bottom Split Bar / Left Background", name: "leftBackground", widget: file}
          - {label: "Bottom Split Bar / Left Second Line", name: "leftTitle", widget: string}
          - {label: "Bottom Split Bar / Left Link", name: "leftLink", widget: string}
          - {label: "Bottom Split Bar / Right Title", name: "rightTitle", widget: string}
          - {label: "Bottom Split Bar / Right Description (Second Line)", name: "rightDescription", widget: string}
          - {label: "Bottom Split Bar / Right Link", name: "rightUrl", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      
  

  